permalink: /:title/
# baseurl: http://ivetteaddington.com

markdown: redcarpet
redcarpet:
  extensions: ['smart', 'superscript']

gems:
   - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
    values:
      lang: en
      layout: default
  -
    scope:
      path: _posts/es 
    values:
      lang: es
  -
    scope:
      path: _posts/es/pages
    values:
      type: pages
  -
    scope:
      path: _posts/en/pages
    values:
      type: pages
  -
    scope:
      path: _posts/es/projects
    values:
      type: projects
  -
    scope: 
      path: _posts/en/projects 
    values:
      type: projects



































